<a href="https://colab.research.google.com/github/2303a51832/B26_1832/blob/main/Lab_03_Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.random.seed(42)
scores = np.random.randint(50, 101, size=(4, 4))
print("Test Scores (4x4 array):")
print(scores)

Test Scores (4x4 array):
[[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]]


In [ ]:
row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)

In [ ]:
std_dev = np.std(scores)
variance = np.var(scores)

In [ ]:
global_max = np.max(scores)
global_min = np.min(scores)

In [ ]:
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)

In [ ]:
print("\nRow-wise Means:", row_means)
print("Column-wise Means:", col_means)


Row-wise Means: [80.5  70.75 66.25 74.75]
Column-wise Means: [75.5  74.25 71.25 71.25]


In [ ]:
print("\nStandard Deviation:", std_dev)
print("Variance:", variance)


Standard Deviation: 12.214073593605043
Variance: 149.18359375


In [ ]:
print("\nGlobal Max Value:", global_max, "at index", max_index)
print("Global Min Value:", global_min, "at index", min_index)


Global Max Value: 92 at index (np.int64(0), np.int64(3))
Global Min Value: 52 at index (np.int64(3), np.int64(3))
