<a href="https://colab.research.google.com/github/2303a51832/B26_1832/blob/main/Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# @title  Create a 2D NumPy array for student marks using 3 subjects
import numpy as np


marks = np.array([
    [85, 90, 78],
    [72, 88, 91],
    [89, 76, 65],
    [95, 92, 98],
    [60, 70, 80]
])

print("Student Marks:\n", marks)


Student Marks:
 [[85 90 78]
 [72 88 91]
 [89 76 65]
 [95 92 98]
 [60 70 80]]


In [2]:
# @title Calculate average, minimum, and maximum marks (student-wise and subject-wise)
print("Student Marks:\n", marks)

average_per_student = np.mean(marks, axis=1)
average_per_subject = np.mean(marks, axis=0)

min_per_student = np.min(marks, axis=1)
max_per_student = np.max(marks, axis=1)

print("\nAverage marks per student:", average_per_student)
print("Average marks per subject:", average_per_subject)

print("Minimum marks per student:", min_per_student)
print("Maximum marks per student:", max_per_student)

Student Marks:
 [[85 90 78]
 [72 88 91]
 [89 76 65]
 [95 92 98]
 [60 70 80]]

Average marks per student: [84.33333333 83.66666667 76.66666667 95.         70.        ]
Average marks per subject: [80.2 83.2 82.4]
Minimum marks per student: [78 72 65 92 60]
Maximum marks per student: [90 91 89 98 80]


In [3]:
# @title  Slicing: Retrieve marks of Student 3 (index 2)
student_3_marks = marks[2]
print("\nMarks of Student 3:", student_3_marks)



Marks of Student 3: [89 76 65]


In [4]:
# @title Boolean indexing: Find students who scored above 80 in any subject
above_80 = marks > 80
print("\nBoolean mask of marks > 80:\n", above_80)


Boolean mask of marks > 80:
 [[ True  True False]
 [False  True  True]
 [ True False False]
 [ True  True  True]
 [False False False]]


In [8]:
students_above_80 = np.any(marks > 80, axis=1)
print("Students scoring above 80 in any subject:", students_above_80)

Students scoring above 80 in any subject: [ True  True  True  True False]


In [7]:
marks_above_80 = marks[students_above_80]
print("Marks of students scoring above 80 in any subject:\n", marks_above_80)


Marks of students scoring above 80 in any subject:
 [[85 90 78]
 [72 88 91]
 [89 76 65]
 [95 92 98]]


In [9]:
# @title Reshape array to observe subject-wise performance
subject_wise = marks.T
print("\nSubject-wise marks (rows: subjects, cols: students):\n", subject_wise)




Subject-wise marks (rows: subjects, cols: students):
 [[85 72 89 95 60]
 [90 88 76 92 70]
 [78 91 65 98 80]]


In [6]:
# @title Comment on the observed results
print("\n--- Observations ---")
print("• Student 4 has the highest overall scores across all subjects.")
print("• Math and Science have higher average scores compared to English.")
print("• Most students scored above 80 in at least one subject.")
print("• Reshaping the array helps to quickly analyze which subject has consistent high or low scores.")


--- Observations ---
• Student 4 has the highest overall scores across all subjects.
• Math and Science have higher average scores compared to English.
• Most students scored above 80 in at least one subject.
• Reshaping the array helps to quickly analyze which subject has consistent high or low scores.
